defaults: &defaults
  offline: false
  secret_token: <%= ENV['COOKIE_SECRET'] %>
  heroku: <%= !!ENV['HEROKU_TYPE'] %>
  api_caching: false
  http_caching: true
  store_exceptions: false
  admins: <%= ENV['ADMINS'].to_s.split(',') %>
  user_agent: <%= ENV['USER_AGENT'] %>
  mongodb:
    uri: <%= ENV['MONGOHQ_URL'] %>
  netflix:
    consumer_key: <%= ENV['NETFLIX_KEY'] %>
    secret: <%= ENV['NETFLIX_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['TWITTER_KEY'] %>
    secret: <%= ENV['TWITTER_SECRET'] %>
  facebook:
    app_id: <%= ENV['FACEBOOK_ID'] %>
    secret: <%= ENV['FACEBOOK_SECRET'] %>
  tmdb:
    api_key: <%= ENV['TMDB_KEY'] %>
  rotten_tomatoes:
    api_key: <%= ENV['ROTTEN_TOMATOES_KEY'] %>

development:
  <<: *defaults
  api_caching: true

test: &testing
  <<: *defaults
  secret_token: <%= "banana" * 5 %>
  mongodb:
    database: movieapp_test
  tmdb:
    api_key: TEST
  rotten_tomatoes:
    api_key: TOMATO

cucumber:
  <<: *testing

production:
  <<: *defaults
  api_caching: true
  store_exceptions: true
